python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_1/" --alpha 1 --gamma 1
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_1/" --alpha 1 --gamma 1
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_2/" --alpha 3 --gamma 1
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_2/" --alpha 3 --gamma 1
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_3/" --alpha 1 --gamma 3
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_3/" --alpha 1 --gamma 3
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_4/" --alpha 6 --gamma 1
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_4/" --alpha 6 --gamma 1
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_5/" --alpha 1 --gamma 6
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_5/" --alpha 1 --gamma 6
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_6/" --alpha 1 --gamma 10
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_6/" --alpha 1 --gamma 10
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_7/" --alpha 3 --gamma 3
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_7/" --alpha 3 --gamma 3
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_8/" --alpha 3 --gamma 6
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_8/" --alpha 3 --gamma 6
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_9/" --alpha 3 --gamma 10
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_9/" --alpha 3 --gamma 10
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_10/" --alpha 6 --gamma 3
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_10/" --alpha 6 --gamma 3
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_11/" --alpha 6 --gamma 6
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_11/" --alpha 6 --gamma 6
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_12/" --alpha 6 --gamma 10
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_12/" --alpha 6 --gamma 10
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_13/" --alpha 10 --gamma 3
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_13/" --alpha 10 --gamma 3
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_14/" --alpha 10 --gamma 6
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_14/" --alpha 10 --gamma 6
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_15/" --alpha 10 --gamma 10
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_15/" --alpha 10 --gamma 10
python3 train_cudnn_with_loss.py --save_dir "/home/shapelim/RONet/loss_term_16/" --alpha 10 --gamma 1
python3 test_cudnn_with_loss.py --load_model_dir "/home/shapelim/RONet/loss_term_16/" --alpha 10 --gamma 1
